package com.rhpam_demo.flow_loan_demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Requester")
public class Requester implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "Age")
	private java.lang.Integer age;
	@org.kie.api.definition.type.Label(value = "Proposed Amount")
	private java.lang.Double proposedAmount;

	public Requester() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Double getProposedAmount() {
		return this.proposedAmount;
	}

	public void setProposedAmount(java.lang.Double proposedAmount) {
		this.proposedAmount = proposedAmount;
	}

	public Requester(java.lang.String name, java.lang.Integer age,
			java.lang.Double proposedAmount) {
		this.name = name;
		this.age = age;
		this.proposedAmount = proposedAmount;
	}

}